package com.unicomer.e_tracker_test.constants



/**
 * Constant values used throughout the app
 */

// FIREBASE TAGS

const val FIREBASE_USER_EMAIL_LOGGED_IN_KEY = ""
const val FIREBASE_USER_UID_KEY = ""
const val FIREBASE_TRAVEL_ID = ""

const val APP_NAME = "UNICOMER_GROUP_E_TRACKER"


// ACTIVITY TAGs

const val LOGIN_ACTIVITY_KEY = "LOGIN_ACTIVITY"
const val MAIN_ACTIVITY_KEY = "MAIN_ACTIVITY"



// FRAGMENT TAGs

const val HOME_FRAGMENT = "HOME_FRAGMENT"
const val REGISTRATION_TRAVEL_FRAGMENT = "TRAVEL_REGISTRATION_FRAGMENT"
const val TERMS_AND_CONDITIONS_FRAGMENT = "TERMS_AND_CONDITIONS_FRAGMENT"
const val ADD_RECORD_FRAGMENT = "ADD_RECORD_FRAGMENT"


// DIALOG TAGS

const val LOGIN_DIALOG = "LOGIN_DIALOG"
const val DELETE_DIALOG = "DELETE_DIALOG"